# Generated by Django 4.1.1 on 2022-10-17 05:42

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('users',
         '0002_user_additional_information_user_address_user_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='additional_information',
            field=models.CharField(blank=True, default=None, max_length=300,
                                   null=True,
                                   verbose_name='Додаткова інформація для доставки'),
        ),
    ]
