# Generated by Django 4.1.1 on 2022-10-21 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('users',
         '0005_alter_user_additional_information_alter_user_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailForNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True,
                                           on_delete=django.db.models.deletion.CASCADE,
                                           related_name='email_for_news',
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
