version: "3.11"

services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./deploy:/src
    env_file:
      - .env
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    restart: always
