version: "3.11"

services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/online_store
    env_file:
      - .env
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    restart: always

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./src:/online_store
    env_file:
      - .env
    links:
      - redis
    depends_on:
      - redis

  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - ./src:/online_store
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"