# Generated by Django 4.1.3 on 2022-11-16 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at', 'title'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
