# Generated by Django 4.1.1 on 2022-10-27 08:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('news',
         '0002_category_title_en_category_title_uk_news_content_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at', 'title'],
                     'verbose_name': 'Новини',
                     'verbose_name_plural': 'Новини'},
        ),
    ]
