# Generated by Django 4.1.1 on 2022-10-24 14:24

import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0012_alter_reviews_unique_together_remove_reviews_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='created',
            field=models.DateTimeField(auto_now_add=True,
                                       default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
