# Generated by Django 4.1.3 on 2023-01-13 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_rename_counnt_reviews_product_count_reviews_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultVarieties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_pk', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('size_pk', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('title_photo', models.CharField(blank=True, default='/media/images/empty/empty.png', max_length=200, null=True)),
                ('color', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_varieties', to='shop.attributecolor')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default_varieties', to='shop.product')),
                ('size', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_varieties', to='shop.attributesize')),
            ],
        ),
    ]
