# Generated by Django 4.1.3 on 2023-01-13 11:38

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_emailfornews_user_alter_emailfornews_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.UserManger()),
            ],
        ),
    ]
