# Generated by Django 4.1.1 on 2022-10-18 05:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('favorite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Favorite',
                     'verbose_name_plural': 'Favorites'},
        ),
    ]
