# Generated by Django 4.1.3 on 2022-11-21 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0002_alter_favorite_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='session_key',
            new_name='user_authenticated',
        ),
    ]
