# Generated by Django 4.1.1 on 2022-10-17 16:49

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_uk',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
