# Generated by Django 4.1.1 on 2022-10-18 05:55

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0005_alter_attributecolor_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='banner',
            name='title_en',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_uk',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='color',
            name='value_en',
            field=models.CharField(blank=True, default=None, max_length=15,
                                   null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='value_uk',
            field=models.CharField(blank=True, default=None, max_length=15,
                                   null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='title_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='title_uk',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='title_uk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='title_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='title_uk',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uk',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='param_en',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='param_uk',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_uk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='title_en',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='title_uk',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
