# Generated by Django 4.1.1 on 2022-10-18 06:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0006_rename_name_delivery_title_banner_title_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributecolor',
            options={'verbose_name': 'Attribute color',
                     'verbose_name_plural': 'Attribute colors'},
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='title_uk',
        ),
    ]
