# Generated by Django 4.1.1 on 2022-10-18 14:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0007_alter_attributecolor_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
