# Generated by Django 4.1.1 on 2022-10-24 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0008_delete_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
                ('rating', models.IntegerField(blank=True,
                                               choices=[(1, 'Дуже погано'),
                                                        (2, 'Погано'),
                                                        (3, 'Нормально'),
                                                        (4, 'Добре'),
                                                        (5, 'Дуже добре')])),
                ('parent',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='shop.reviews')),
                ('product',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='rewiews',
                                   to='shop.product')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='reviews',
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
