# Generated by Django 4.1.1 on 2022-10-25 03:53

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0013_reviews_created_reviews_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='counnt_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=0, default=5,
                                      max_digits=10),
        ),
    ]
