# Generated by Django 4.1.1 on 2022-10-20 06:41

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0003_promocode_alter_order_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='promo_code',
            field=models.CharField(blank=True, default=None, max_length=200,
                                   null=True),
        ),
    ]
