# Generated by Django 4.1.1 on 2022-10-20 10:47

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0008_delete_status'),
        ('orders', '0007_alter_goodsintheorder_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsintheorder',
            name='color',
            field=models.ForeignKey(blank=True, default=None, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='shop.attributecolor'),
        ),
        migrations.AddField(
            model_name='goodsintheorder',
            name='size',
            field=models.ForeignKey(blank=True, default=None, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='shop.attributesize'),
        ),
    ]
