# Generated by Django 4.1.1 on 2022-10-17 16:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinbasket',
            options={'verbose_name': 'Goods in the basket',
                     'verbose_name_plural': 'Goods in the basket'},
        ),
    ]
